### ISSUE TITLE
Add a "not supported error" (instead of crashing) for QuerySet.aggregate()

### ISSUE THREAD

**Issue by timgraham** [mongodb-labs/django-mongodb#10]
For example:
```
./tests/runtests.py from_db_value.tests.FromDBValueTest.test_aggregation
Testing against Django installed in '/home/tim/code/django/django' with up to 3 processes
Found 1 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
E
======================================================================
ERROR: test_aggregation (from_db_value.tests.FromDBValueTest.test_aggregation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tim/code/django/tests/from_db_value/tests.py", line 26, in test_aggregation
    maximum = CashModel.objects.aggregate(m=Max("cash"))["m"]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/code/django/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/code/django/django/db/models/query.py", line 604, in aggregate
    return self.query.chain().get_aggregation(self.db, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/code/django/django/db/models/sql/query.py", line 620, in get_aggregation
    result = next(compiler.apply_converters((result,), converters))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/code/django/django/db/models/sql/compiler.py", line 1500, in apply_converters
    value = converter(value, expression, connection)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/code/django-mongodb/django_mongodb/operations.py", line 38, in convert_decimalfield_value
    value = decimal.Decimal(value)
            ^^^^^^^^^^^^^^^^^^^^^^
TypeError: conversion from dict to Decimal is not supported
```
It's probably complicated (impossible?) to implement full aggregate support, but for now it should not crash.

**Comment by timgraham** [comment]
Done:https://github.com/mongodb-labs/django-mongodb/blob/28f52b14bc6eab9eca3bebaa7241e46848deab90/django_mongodb/compiler.py#L108-L112

https://github.com/mongodb-labs/django-mongodb/issues/12 is open for adding aggregate support.
